default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      device: "iPhone 17 Pro Max",
      scheme: "BSGAsyncImage",
      testplan: "BSGAsyncImageTests",
      workspace: "BSGAsyncImage.xcworkspace" 
    )
  end
end
