name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Ruby Setup
      run: |
        gem install bundler
        bundle install
    - name: Test BSGImageLoader
      run: bundle exec fastlane test
